function boundaryterm=AddMomRHS_Boundary(Mesh,Field,Fluid)
    %{
    - Unlike Ash's code, Field.face.velosity is used instead of
      Mesh.face.boundarycondition
    %}
    boundaryterm=zeros(Mesh.element.number,Mesh.Dimension);
    
    for i=1:Mesh.face.boundarynum
        switch Mesh.face.boundarycondition(i,1)
            case 1 %Specific pressure
                BoundaryVelocity=zeros(1,3);
                for k=1:Mesh.Dimension
                    BoundaryVelocity(k)...
                   =Field.element.velocity(Mesh.face.owner(i,1),k)...
                   +dot(Field.face.velocitygrad(i,3*k-2:3*k),...
                        Mesh.face.dCF(i)*Mesh.face.ecf(i,:)...
                        );
                end
                for k=1:Mesh.Dimension
                    boundaryterm(Mesh.face.owner(i,1),k)...
                   =boundaryterm(Mesh.face.owner(i,1),k)...
                   -Fluid.density*dot(BoundaryVelocity,Mesh.face.Sf(i,:))...
                   *dot(Field.face.velocitygrad(i,3*k-2:3*k),Mesh.face.dCF(i)*Mesh.face.ecf(i,:));
                end
            case 2  %Specific velocity
                for k=1:Mesh.Dimension
                    boundaryterm(Mesh.face.owner(i,1),k)...
                   =boundaryterm(Mesh.face.owner(i,1),k)...
                   +(...
                     max(Field.face.flux(i),0)+Fluid.viscosity*Mesh.face.Ef(i)/Mesh.face.dCF(i)...
                    )*Field.face.velocity(i,k);
                end
                
            case 3  %No slip wall, (15.123)-(15.126)
                for k=1:Mesh.Dimension
                    boundaryterm(Mesh.face.owner(i,1),k)...
                   =boundaryterm(Mesh.face.owner(i,1),k)...
                   +Fluid.viscosity*Mesh.face.area(i)/Mesh.face.dCF(i)...
                   *(Field.face.velocity(i,k)...
                   +dot(Field.element.velocity(Mesh.face.owner(i,1),:)-Field.face.velocity(i,:),Mesh.face.Sf(i,:)/Mesh.face.area(i))...
                   *Mesh.face.Sf(i,k)/Mesh.face.area(i));
                end
                
            case 4 %Slip wall
                disp('Slip wall, Undefined Boundary Condition')
            otherwise
                disp('Undefined Boundary Condition in AddBoundaryMomRHS.m')
        end
    end
%     dlmwrite('boundarytermRHS.txt',boundaryterm);
end