function preallocate()
    global Domain
    Domain.Field.element=struct('pressure',zeros(Domain.Mesh.element.number,1),...
                                'PCorrect',zeros(Domain.Mesh.element.number,1),...
                                'velocity',zeros(Domain.Mesh.element.number,3),...
                                'lastvelocity',zeros(Domain.Mesh.element.number,3),...
                                'velocitygrad',zeros(Domain.Mesh.face.number,9),...
                                'pressuregrad',zeros(Domain.Mesh.element.number,3),...
                                'PCorrectgrad',zeros(Domain.Mesh.element.number,3));
    Domain.Field.face   =struct('pressure',zeros(Domain.Mesh.face.number,1),...
                                'pressuregrad',zeros(Domain.Mesh.face.number,3),...
                                'PCorrectgrad',zeros(Domain.Mesh.face.number,3),...
                                'flux',zeros(Domain.Mesh.face.number,1),...
                                'velocity',zeros(Domain.Mesh.face.number,3),...
                                'velocitygrad',zeros(Domain.Mesh.face.number,9));
    Domain.Tmp          =struct('res_veloc',0,'res_p',0);
end