function HOterm=ScalarRHS_HigherOrder(Mesh,Field)
    HOterm=zeros(Mesh.element.number,1);
    
     for i=Mesh.face.boundarynum+1:Mesh.face.number
        HOterm(Mesh.face.owner(i,1))...
       =-max(Field.face.flux(i),0)*(1/2)...
        *dot(...
             Field.element.scalar1grad(Mesh.face.owner(i,1),:)+Field.face.scalar1grad(i,:)...
            ,Mesh.face.dCf(i)*Mesh.face.ecf(i,:)...
            )...
        -max(-Field.face.flux(i),0)*(1/2)...
        *dot(...
             Field.element.scalar1grad(Mesh.face.owner(i,2),:)+Field.face.scalar1grad(i,:)...
            ,-Mesh.face.dCf(i)*Mesh.face.ecf(i,:)...
            );
        
        HOterm(Mesh.face.owner(i,2))...
       =max(Field.face.flux(i),0)*(1/2)...
        *dot(...
             Field.element.scalar1grad(Mesh.face.owner(i,1),:)+Field.face.scalar1grad(i,:)...
            ,Mesh.face.dCf(i)*Mesh.face.ecf(i,:)...
            )...
        +max(-Field.face.flux(i),0)*(1/2)...
        *dot(...
             Field.element.scalar1grad(Mesh.face.owner(i,2),:)+Field.face.scalar1grad(i,:)...
            ,-Mesh.face.dCf(i)*Mesh.face.ecf(i,:)...
            );
    end
end